# Generated by Django 2.0 on 2017-12-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplestatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
