# Generated by Django 2.0.7 on 2018-07-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplestatistics', '0009_auto_20180625_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoricalInstance',
            fields=[
                ('probleminstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samplestatistics.ProblemInstance')),
                ('categorical_list', models.TextField()),
            ],
            bases=('samplestatistics.probleminstance',),
        ),
        migrations.CreateModel(
            name='CategoricalProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samplestatistics.Problem')),
                ('categorical_num_rands_low', models.IntegerField()),
                ('categorical_num_rands_high', models.IntegerField()),
            ],
            bases=('samplestatistics.problem',),
        ),
        migrations.CreateModel(
            name='TwoListInstance',
            fields=[
                ('probleminstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samplestatistics.ProblemInstance')),
                ('second_numbers', models.CharField(max_length=200)),
            ],
            bases=('samplestatistics.probleminstance',),
        ),
        migrations.CreateModel(
            name='TwoListProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samplestatistics.Problem')),
                ('second_random_low', models.IntegerField()),
                ('second_random_high', models.IntegerField()),
                ('second_num_rands_low', models.IntegerField()),
                ('second_num_rands_high', models.IntegerField()),
                ('second_spread', models.IntegerField()),
            ],
            bases=('samplestatistics.problem',),
        ),
        migrations.AddField(
            model_name='problem',
            name='spread',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
