# Generated by Django 2.0.1 on 2018-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvasaheim', '0008_auto_20180625_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='equation',
            field=models.TextField(default='def solve(x):\n    return x'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='excel',
            field=models.TextField(default='<div class="excel code">\n</div>'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rcode',
            field=models.TextField(default='<div class="r code">\n</div>'),
        ),
    ]
