# Generated by Django 2.0.7 on 2018-08-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvasaheim', '0012_auto_20180720_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorical', models.BooleanField(default=False)),
                ('random_low', models.IntegerField(default=10)),
                ('random_high', models.IntegerField(default=100)),
                ('num_rands_low', models.PositiveIntegerField(default=5)),
                ('num_rands_high', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoricalinstance',
            name='probleminstance_ptr',
        ),
        migrations.RemoveField(
            model_name='categoricalproblem',
            name='problem_ptr',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twolistinstance',
            name='probleminstance_ptr',
        ),
        migrations.RemoveField(
            model_name='twolistproblem',
            name='problem_ptr',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='num_rands_high',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='num_rands_low',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='random_high',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='random_low',
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', related_query_name='problems', to='kvasaheim.Category'),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='numbers',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='CategoricalInstance',
        ),
        migrations.DeleteModel(
            name='CategoricalProblem',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TwoListInstance',
        ),
        migrations.DeleteModel(
            name='TwoListProblem',
        ),
        migrations.AddField(
            model_name='category',
            name='realm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', related_query_name='categories', to='kvasaheim.Realm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='generators',
            field=models.ManyToManyField(related_name='generator', related_query_name='generators', to='kvasaheim.Generator'),
        ),
    ]
