# Generated by Django 2.0.7 on 2018-08-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvasaheim', '0013_auto_20180819_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='categorical',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='lists',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='numbers',
            field=models.CharField(max_length=1000),
        ),
    ]
