# Generated by Django 2.0.7 on 2018-08-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvasaheim', '0014_auto_20180821_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='title',
            field=models.CharField(max_length=200, blank=True),
        ),
    ]
