# Generated by Django 2.0.7 on 2018-09-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvasaheim', '0015_auto_20180821_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='formula',
            field=models.TextField(default='<div style="margin:0 0 2em 2em;">'),
        ),
    ]
